name = "atomic-url"
type = "webpack"

account_id = "f3c91ba96531ef2a0d935cb0e25a2f2d"
compatibility_date = "2021-12-29"
kv_namespaces = [
  {binding = "URL_DB", id = "cdde69eec3d5465ab1e6a44ddde79403", preview_id = "79d78420f110421ea6f433697d8f0202"},
]
route = ""
workers_dev = true
zone_id = "033fe9c10f95302e2bd63fd5b9093602"

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"
